---
name: "L2 S-NRHO to L2 N-NRHO Transfer"
description: "NRHO to NRHO transfer with small execution errors and small initial/final covariance, limited phasing"
dynamics:
  type: "CR3BP"
  sys_param_file: '../CR3BP_dev/EarthMoon_System/EMsys.yaml'
integration:
  a_tol: 1.e-14
  r_tol: 1.e-14
traj_parameters:
  control_arcs: 40
  save_pts_detailed: 12
  MC_trials: 1000
boundary_conditions:
  t0: "2026-01-01T00:00:00"
  tf: "2026-01-11T00:00:00"
  initial_orbit:
    family_path: '../CR3BP_dev/EarthMoon_System/L2_S_Halo.h5'
    Orb_ID: 323
    Start_Idx: 0
  final_orbit:
    family_path: '../CR3BP_dev/EarthMoon_System/L2_N_Halo.h5'
    Orb_ID: 323
    Start_Idx: 0
  type: "free"
  alpha:
    min: 0.0
    max: 0.1
  beta:
    min: 0.0
    max: 0.1
engine:
  m0: 200
  Isp: 3337
  T_max: .5
uncertainty:
  covariance:
    initial:
      pos_sig: 1
      vel_sig: .01
      mass_sig: 1.e-12
    target:
      pos_sig: 10
      vel_sig: .02
      mass_sig: 60
  acc_sig: 5.e-12
  gates:
    fixed_mag: 1.e-3
    prop_mag: 1.e-3
    fixed_point: 1.e-3
    prop_point: 1.e-3
  tcm_stat_bound: .999
  dV_bound: .99
constraints: 
  col_avoid:
    parameters:
      r_obs: [384967.8803361727, 0., 0.]
      safe_d: 1737.5
    det:
      bool: true
    stat:
      bool: false
      UT:
        alpha: 1.0
        beta: 2.0
        kappa: 4.0
SNOPT:
  major_opt_tol: 1.e-5 # Pretty much always keep this at 1.e-5 (linesearch_tol is more important)
  major_feas_tol: 1.e-6
  minor_feas_tol: 1.e-6
  major_iter_limit: 2000
  partial_price: 10  # 1 for deterministic, 10 for stochastic
  linesearch_tol: .05 # .99 for deterministic, .05 for stochastic
  function_prec: 1e-12