---
name: "L1 N-Halo to L2 S-Halo"
description: "IDK whaever... this is just random testing, go see the other scenarios for real stuff"
dynamics:
  type: "CR3BP"
  sys_param_file: '../CR3BP_dev/EarthMoon_System/EMsys.yaml'
integration:
  a_tol: 1.e-13
  r_tol: 1.e-13
traj_parameters:
  control_arcs: 40
  sub_arcs: 1
  save_pts_detailed: 51
  MC_trials: 1000
boundary_conditions:
  t0: "2026-01-01T00:00:00"
  tf: "2026-01-21T00:00:00"
  tf_T: 5
  initial_orbit:
    family_path: '../CR3BP_dev/EarthMoon_System/L1_N_Halo.h5'
    Orb_ID: 200
    Start_Idx: 0
  final_orbit:
    family_path: '../CR3BP_dev/EarthMoon_System/L2_S_Halo.h5'
    Orb_ID: 310
    Start_Idx: 0
  type: "free"
  alpha:
    min: .0
    max: .5
  beta:
    min: .0
    max: .5
engine:
  m0: 200
  Isp: 3337
  T_max: .5
uncertainty:
  covariance:
    initial_dispersion:
      pos_sig: 10
      vel_sig: .001
      mass_sig: 1.e-12
    initial_error:
      pos_sig: 0.
      vel_sig: 0.
      mass_sig: 0.
    post_insert_target_total:
      pos_sig: 150
      vel_sig: .01
      mass_sig: 60
  acc_sig: 5.e-12
  measurement:
    type: 'position_test'
    observer_body: 'r2'
    observer_alt_lat_lon: [6371., 0., 0.]
    range_sig: 1.e-4
    pos_sig: 1.e-4
  gates:
    fixed_mag: 1.e-3
    prop_mag: 1.e-3
    fixed_point: 1.e-3
    prop_point: 1.e-3
  tcm_stat_bound: .999
  dV_bound: .99
constraints: 
  col_avoid:
    parameters:
      obj_body: 'r2'
      safe_d: 5000
    det:
      bool: True
    stat:
      bool: False
      bound: .999
      UT:
        alpha: 1.0
        beta: 2.0
        kappa: 4.0